### ISSUE TITLE
sample on mac needs updating

### ISSUE THREAD

**Issue by brucelane** [brucelane/Cinder-MIDI2#10]
hi Martin,
I've tested on Mac, there are errors with boost for Cinder 0.9

**Comment by felixfaire** [comment]
Any further thoughts on how to resolve these errors?

Do you forsee any threading issues with using cinder/Signals instead of boost/signals2 for example to eliminate the boost dependancy?

**Comment by brucelane** [comment]
we should get rid of boost in this block, I was thinking of using std, but if you got a better idea?

**Comment by brucelane** [comment]
I using this block on Windows, but I would like to update it on Mac and Linux too, although I can test on Mac and Linux, I'm not up to speed yet on those platforms...

**Comment by felixfaire** [comment]
I'm not super knowledgable about this but I know cinder has implemented cinder/Signals to remove most of their dependancies on boost/signals2. The primary difference being that boost/signals2 is threadsafe whereas cinder/Singals is not.

I dont know enough about the structure of this block but if we know the midi messages come through on the same thread as the main app loop (ie where the callback function will be called) then I imagine it will be safe to use cinder/Signals instead like the rest of cinder.

However if the midi messages are coming in on a seperate thread we might want to use something else (ci::app::App::dispatchAsync(...) ? ).

Do you know the threading situation for this block and RTMidi?

**Comment by brucelane** [comment]
let's use cinder/Signals to check?
I have written this block, so I don't know much about the threading part.
I use it all the time in a live performance situation without problem, it's stable.

**Comment by felixfaire** [comment]
A quick look at how JUCE does things implies midi messages will likely be coming from background threads from the OS so it might be worthwhile looking into dispatchAsync when emitting the process midi signal.

**Comment by brucelane** [comment]
sounds good

**Comment by felixfaire** [comment]
I think this can be closed too now.

**Comment by brucelane** [comment]
thank you @felixfaire !
