### ISSUE TITLE
cinder/Signals thread safety

### ISSUE THREAD

**Issue by felixfaire** [brucelane/Cinder-MIDI2#13]
Replacing boost/signals2 with cinder/Signals has worked on the surface but raised some flags about thread safety.

We may want to pipe midi messages through a lockfree fifo or use Cinder's ConcurrentCircularBuffer to ensure the midi messages get onto the main thread safely.

**Comment by brucelane** [comment]
ConcurrentCircularBuffer or a LIFO ?
How about a LIFO for each midi note/ctrl?

**Comment by felixfaire** [comment]
Having said this, I just checked the older version that used boost/signals2 and `midiListener(midi::Message msg)`
was getting called on the separate midi thread anyway! So actually the new implementation is no worse than the old one (it seems) but they are still not good.

**Comment by felixfaire** [comment]
Looks like my optional async callbacks made it into the last PR so this can be closed. Let me know if you you notice any performance issues (I havent yet) with the thread safe option (now in the example). However the old callbacks are still there just renamed to mMidiThreadSignal (to imply the signal will be called from the midi thread rather than the main one).
