### ISSUE TITLE
xcode sample, issue with RendererGL

### ISSUE THREAD

**Issue by lhilbert** [brucelane/Cinder-MIDI2#7]
Had to comment out 
# include "cinder/app/RendererGl.h"

in sampleApp.cpp for the xcode sample to compile. (with cinder_0.8.6_mac)

After that it compiles and seems to run fine.

**Comment by MartinBspheroid** [comment]
Sorry for totally  late reply... but yeah :+1: I was not using this or maintained this repo for quite while, so users were pretty much on their own. As I'm in need for midi controls in upcoming projects, I'm going to fix it

**Comment by felixfaire** [comment]
Xcode sample works now
